title: Rezina Bhatta Portfolio
description: A personal student portfolio showcasing projects,
baseurl: ""
Url: 
theme: jeklly-theme-minimal
author: 
 name: Bhatta Rezina
 email: bhattarezina07@gmail.com
